-- Pure Lua 5.1 regression tests. Run: lua Tests/run.lua
local passed, failed = 0, 0
local function check(name, condition) if condition then passed=passed+1 else failed=failed+1; io.stderr:write("FAIL: "..name.."\n") end end
local function equals(a,b) return a == b end
_G.WOW_PROJECT_ID=1; _G.WOW_PROJECT_MAINLINE=1; _G.GetLocale=function()return "enUS"end; _G.time=function()return 100 end; _G.date=function()return "2026-07-15"end; _G.InCombatLockdown=function()return _G.__combat or false end;_G.GetFramerate=function()return 60 end
_G.IsGraphicsSettingValueSupported=function()return nil end;_G.IsGraphicsCVarValueSupported=function()return nil end;_G.AntiAliasingSupported=function()return true,true,true end
local store={}; _G.C_CVar={GetCVar=function(k)return store[k] end,GetCVarInfo=function(k)if store[k]~=nil then return store[k],store[k],false,false,false,false,false end end,SetCVar=function(k,v)store[k]=v;return true end};_G.C_VideoOptions={IsSpellVisualDensitySystemSupported=function()return true end};_G.GetBuildInfo=function()return "12.0.7","68453","",120007 end
local addon,ns="STierBlizzSettings",{}
local files={"Core/Constants.lua","Localization/enUS.lua","Localization/ruRU.lua","Localization/frFR.lua","Localization/deDE.lua","Localization/esES.lua","Localization/esMX.lua","Localization/ptBR.lua","Localization/koKR.lua","Localization/zhCN.lua","Localization/zhTW.lua","Localization/NewUI.lua","Localization/UITweaks.lua","Core/Bootstrap.lua","Core/Compatibility.lua","Core/Database.lua","Core/FPSBenchmark.lua","Core/ZoneGraphics.lua","UI/Style.lua","Settings/Registry.lua","Settings/Validator.lua","Settings/Reader.lua","Settings/Writer.lua","Settings/Diff.lua","Settings/Backup.lua","Profiles/Schema.lua","Profiles/Migration.lua","Profiles/Recommended.lua","Profiles/Manager.lua","UI/PerformanceWidget.lua","ImportExport/Serializer.lua","ImportExport/Codec.lua","ImportExport/Validation.lua","Settings/Transaction.lua","Core/UITweaks.lua"}
for _,f in ipairs(files)do assert(loadfile("STierBlizzSettings/"..f))(addon,ns)end
local oldCreateFrame=_G.CreateFrame;_G.Minimap={GetWidth=function()return 140 end};_G.CreateFrame=function()return {SetSize=function()end,SetFrameStrata=function()end,SetFrameLevel=function()end,SetPoint=function()end,ClearAllPoints=function()end,SetNormalTexture=function()end,SetHighlightTexture=function()end,SetPushedTexture=function()end,RegisterForClicks=function()end,RegisterForDrag=function()end,CreateTexture=function()return {SetTexture=function()end,SetSize=function()end,SetPoint=function()end}end,SetScript=function(self,event,handler)self[event]=handler end}end;assert(loadfile("STierBlizzSettings/Core/MinimapButton.lua"))(addon,ns)
local opened=false;ns.ShowGraphics=function()opened="graphics" end;ns.ShowProfiles=function()opened="profiles" end;ns:CreateMinimapButton();check("minimap button is created",ns.minimapButton~=nil);ns.minimapButton.OnClick(nil,"LeftButton");check("minimap left click opens graphics",opened=="graphics");ns.minimapButton.OnClick(nil,"RightButton");check("minimap right click opens profiles",opened=="profiles");_G.CreateFrame=oldCreateFrame
for _,setting in ipairs(ns.Registry)do local chosen=nil;if setting.validValues then for value in pairs(setting.validValues)do if not chosen or tonumber(value)<tonumber(chosen) then chosen=value end end else chosen=tostring(setting.numericMinimum or 0)end;if setting.minimum then chosen=tostring(setting.minimum) end;store[setting.key]=chosen end
ns:InitializeDatabase()
check("French client uses French localization",(function()_G.GetLocale=function()return "frFR"end;return ns:L("HOME")=="Accueil"end)())
check("unsupported client locale falls back to English",(function()_G.GetLocale=function()return "itIT"end;return ns:L("HOME")=="Home"end)())
_G.GetLocale=function()return "enUS"end
for _,locale in ipairs({"ruRU","frFR","deDE","esES","esMX","ptBR","koKR","zhCN","zhTW"}) do for key in pairs(ns.Locale.enUS) do check(locale.." localization contains "..key,ns.Locale[locale][key]~=nil) end;_G.GetLocale=function()return locale end;check(locale.." FPS result format is valid",pcall(ns.FormatFPSMetric,ns,{before=74,after=91,delta=17,percent=23})) end
for _,locale in ipairs({"enUS","enGB","ruRU","frFR","deDE","esES","esMX","ptBR","koKR","zhCN","zhTW"}) do check("client locale resolves "..locale,(function()_G.GetLocale=function()return locale end;return ns:L("HOME")~=nil end)()) end
_G.GetLocale=function()return "enUS"end
check("registry contains base and raid settings",#ns.Registry>=32 and ns.RegistryByKey.graphicsShadowQuality~=nil and ns.RegistryByKey.raidGraphicsShadowQuality~=nil)
check("registry contains verified combat readability settings",ns.RegistryByKey.countdownForCooldowns~=nil and ns.RegistryByKey.showTargetOfTarget~=nil and ns.RegistryByKey.nameplateShowEnemies~=nil)
check("registry contains verified UI tweak CVars",ns.RegistryByKey.ResampleAlwaysSharpen and ns.RegistryByKey.ResampleSharpness and ns.RegistryByKey.ffxGlow and ns.RegistryByKey.ffxDeath and ns.RegistryByKey.ffxNether)
local originalGetInfo=_G.C_CVar.GetCVarInfo;_G.C_CVar.GetCVarInfo=function()error("removed")end;check("removed CVar info fails closed",not ns:CanUseCVar("removed"));_G.C_CVar.GetCVarInfo=originalGetInfo
local originalGet=_G.C_CVar.GetCVar;_G.C_CVar.GetCVar=function()error("removed")end;check("removed CVar read fails closed",ns:ReadSetting(ns.RegistryByKey.cameraSmoothStyle)==nil);_G.C_CVar.GetCVar=originalGet
local originalSet=_G.C_CVar.SetCVar;_G.C_CVar.SetCVar=function()error("rejected")end;check("throwing CVar write fails closed",not ns:WriteSetting(ns.RegistryByKey.cameraSmoothStyle,"1"));_G.C_CVar.SetCVar=originalSet
store.cameraSmoothStyle="1";_G.C_CVar.GetCVarInfo=function(k)if k=="cameraSmoothStyle"then return store[k],store[k],false,false,true,false,false end;return originalGetInfo(k)end;local lockedPlan=ns:BuildDiff({cameraSmoothStyle="0"});check("locked CVar is previewed as unavailable instead of written",lockedPlan[1].status=="unavailable");_G.C_CVar.GetCVarInfo=originalGetInfo
check("shadow quality accepts 5",ns:ValidateValue(ns.RegistryByKey.graphicsShadowQuality,"5"));check("shadow quality rejects 6",not ns:ValidateValue(ns.RegistryByKey.graphicsShadowQuality,"6"));check("liquid detail rejects 4",not ns:ValidateValue(ns.RegistryByKey.graphicsLiquidDetail,"4"));check("camera excludes 3",not ns:ValidateValue(ns.RegistryByKey.cameraSmoothStyle,"3"));check("texture filtering accepts 0",ns:ValidateValue(ns.RegistryByKey.textureFilteringMode,"0"))
for _,setting in ipairs(ns.Registry)do if setting.validValues then for value in pairs(setting.validValues)do if not setting.minimum or tonumber(value)>=setting.minimum then check("registry valid "..setting.key.."="..value,ns:ValidateValue(setting,value))end end end end
check("resample sharpness accepts the documented Blizzard range",ns:ValidateValue(ns.RegistryByKey.ResampleSharpness,"0.3") and ns:ValidateValue(ns.RegistryByKey.ResampleSharpness,"2.0") and not ns:ValidateValue(ns.RegistryByKey.ResampleSharpness,"2.1"));check("resample float verification tolerates client normalization",ns:SettingValuesEqual(ns.RegistryByKey.ResampleSharpness,"0.29999995","0.3"))
check("unsafe base projected textures rejected",not ns:ValidateSettings({graphicsProjectedTextures="0"},true));check("unsafe raid projected textures rejected",not ns:ValidateSettings({graphicsProjectedTextures="1",raidGraphicsProjectedTextures="0"},true));check("unsafe base particle rejected",not ns:ValidateSettings({graphicsParticleDensity="0"},true));check("unsafe raid outline rejected",not ns:ValidateSettings({raidGraphicsOutlineMode="0"},true))
check("personal profiles may preserve visibility values below official minimum",ns:ValidateSettings({graphicsProjectedTextures="0",graphicsParticleDensity="0",graphicsOutlineMode="0"},false))
_G.STierBlizzSettingsDB.preferences.graphicsMode=nil;store.RAIDsettingsEnabled="1";local derivedModeProfile=ns:SaveCurrent("Detected raid mode",{graphics=true});check("saving graphics derives the active Blizzard raid mode before preset selection",derivedModeProfile and derivedModeProfile.sections.graphics.mode==ns.GRAPHICS_MODE_SPLIT)
ns:SetSelectedMode("unified");check("invalid graphics mode rejected",not ns:SetSelectedMode("invalid"));local unified=ns:FlattenProfile(ns:GetOfficialGraphics("unified"),{graphics=true});check("unified disables raid",unified.RAIDsettingsEnabled=="0");local split=ns:FlattenProfile(ns:GetOfficialGraphics("split"),{graphics=true});check("split includes raid",split.RAIDsettingsEnabled=="1" and split.raidGraphicsProjectedTextures=="1")
local pro=ns:FlattenProfile(ns:GetOfficialGraphics("split",ns.GRAPHICS_PRESET_PRO),{graphics=true});local optimized=ns:FlattenProfile(ns:GetOfficialGraphics("split",ns.GRAPHICS_PRESET_OPTIMIZED),{graphics=true});local quality=ns:FlattenProfile(ns:GetOfficialGraphics("split",ns.GRAPHICS_PRESET_QUALITY),{graphics=true});check("three presets keep combat visibility while scaling expensive settings",pro.graphicsProjectedTextures=="1" and pro.graphicsOutlineMode=="2" and tonumber(quality.graphicsViewDistance)>tonumber(pro.graphicsViewDistance) and quality.graphicsTextureResolution=="2");check("PRO uses Essential spell density and minimum environment detail",pro.graphicsSpellDensity=="0" and pro.raidGraphicsSpellDensity=="0" and pro.graphicsEnvironmentDetail=="1" and pro.raidGraphicsEnvironmentDetail=="1");check("all presets minimize decorative ground clutter",pro.graphicsGroundClutter=="1" and pro.raidGraphicsGroundClutter=="1" and optimized.graphicsGroundClutter=="1" and optimized.raidGraphicsGroundClutter=="1" and quality.graphicsGroundClutter=="1" and quality.raidGraphicsGroundClutter=="1")
for _,item in ipairs({{ns.GRAPHICS_PRESET_PRO,pro},{ns.GRAPHICS_PRESET_OPTIMIZED,optimized},{ns.GRAPHICS_PRESET_QUALITY,quality}})do for key,value in pairs(item[2])do store[key]=value end;check("current graphics detects applied preset "..item[1],ns:GetCurrentGraphicsPreset()==item[1])end;store.graphicsShadowQuality="1";check("current graphics becomes Custom after a manual difference",ns:GetCurrentGraphicsPreset()==nil);for key,value in pairs(pro)do store[key]=value end
for _,preset in ipairs({ns.GRAPHICS_PRESET_PRO,ns.GRAPHICS_PRESET_OPTIMIZED,ns.GRAPHICS_PRESET_QUALITY}) do local settings=ns:FlattenProfile(ns:GetOfficialGraphics("split",preset),{graphics=true});check("official graphics preset validates safely: "..preset,ns:ValidateSettings(settings,true)) end
local interfaceRecommended=ns:FlattenProfile(ns:GetOfficialInterface(),{interfaceGameplay=true});check("official interface profile improves combat readability",interfaceRecommended.cameraSmoothStyle=="0" and interfaceRecommended.countdownForCooldowns=="1" and interfaceRecommended.showTargetOfTarget=="1" and interfaceRecommended.occludedSilhouettePlayer=="1" and interfaceRecommended.nameplateShowEnemies=="1" and interfaceRecommended.nameplateShowAll=="1" and interfaceRecommended.nameplateShowOffscreen=="1")
local originalGraphicsValidator=_G.IsGraphicsSettingValueSupported;_G.IsGraphicsSettingValueSupported=function(key,value)return key=="graphicsShadowQuality" and value==5 and 1 or nil end;local supported,unsupportedWhy=ns:ValidateValue(ns.RegistryByKey.graphicsShadowQuality,"5");check("hardware-unsupported graphics value fails closed",not supported and unsupportedWhy=="unsupported");_G.IsGraphicsSettingValueSupported=originalGraphicsValidator
_G.AntiAliasingSupported=function()return true,true,true end;check("AA prefers CMAA2",ns:GetPreferredAntiAliasing().ffxAntiAliasingMode=="4");_G.AntiAliasingSupported=function()return true,true,false end;check("AA falls back CMAA",ns:GetPreferredAntiAliasing().ffxAntiAliasingMode=="3");check("unsupported imported CMAA2 fails closed",not ns:ValidateValue(ns.RegistryByKey.ffxAntiAliasingMode,"4"));_G.AntiAliasingSupported=function()return true,false,false end;check("AA falls back FXAA High",ns:GetPreferredAntiAliasing().ffxAntiAliasingMode=="2");_G.AntiAliasingSupported=nil;check("AA preserves when capability unavailable",ns:GetPreferredAntiAliasing()==nil)
store.graphicsShadowQuality="1";store.cameraSmoothStyle="1";local saved=ns:SaveCurrent("Round trip",{graphics=true,interfaceGameplay=true});local export=ns:ExportProfile(saved,{graphics=true,interfaceGameplay=true});local payload,why=ns:ImportProfile(export);check("complete save export import roundtrip",payload and payload.profile.id==saved.id);local plan,planned=ns:PlanImport(payload,{graphics=true,interfaceGameplay=false},"current");check("module-selective import plan",#plan>0 and planned.cameraSmoothStyle==nil);check("profile mode preservation",planned.RAIDsettingsEnabled=="0")
local secondSaved=ns:SaveCurrent("Round trip 2",{graphics=true});check("personal profile ids are collision-safe within one second",secondSaved and secondSaved.id~=saved.id)
local bundle,bundleWhy=ns:ExportAddonBundle();local importedBundle,importedBundleWhy=ns:ImportAddonBundle(bundle);check("full addon settings bundle roundtrips as data only",bundle and not bundleWhy and bundle:sub(1,#ns.ADDON_EXPORT_PREFIX)==ns.ADDON_EXPORT_PREFIX and importedBundle and not importedBundleWhy and importedBundle.preferences.graphicsMode==ns:GetSelectedMode() and importedBundle.profiles[saved.id]~=nil and importedBundle.graphicsSettings.graphicsShadowQuality~=nil and importedBundle.uiTweaksSettings.ResampleSharpness~=nil);check("tampered addon bundle is rejected",not ns:ImportAddonBundle(bundle:sub(1,-2)..(bundle:sub(-1)=="0" and "1" or "0")))
local function encodeAddonPayload(value)local raw=ns:Serialize(value);return ns.ADDON_EXPORT_PREFIX..ns:Checksum(raw)..":"..ns:Base64Encode(raw)end;local legacyBundlePayload=ns:Copy(importedBundle);legacyBundlePayload.uiTweaksSettings=nil;local legacyBundle=ns:ImportAddonBundle(encodeAddonPayload(legacyBundlePayload));check("older full addon bundles without UI Tweaks remain compatible",legacyBundle and type(legacyBundle.uiTweaksSettings)=="table" and not next(legacyBundle.uiTweaksSettings));local hostileTweaks=ns:Copy(importedBundle);hostileTweaks.uiTweaksSettings={unknownHiddenCVar="1"};check("full addon import rejects UI Tweaks outside the allowlist",not ns:ImportAddonBundle(encodeAddonPayload(hostileTweaks)));local invalidSharpness=ns:Copy(importedBundle);invalidSharpness.uiTweaksSettings.ResampleSharpness="2.1";check("full addon import rejects invalid UI Tweak values",not ns:ImportAddonBundle(encodeAddonPayload(invalidSharpness)))
local oldWidgetSetter=ns.SetPerformanceWidgetEnabled;ns.SetPerformanceWidgetEnabled=function(_,enabled)ns.__widgetEnabled=enabled end;store.graphicsShadowQuality="5";local bundleApply=ns:ApplyAddonBundle(importedBundle);check("full addon import applies graphics backup-first and restores addon preferences",bundleApply.ok and store.graphicsShadowQuality==importedBundle.graphicsSettings.graphicsShadowQuality and _G.STierBlizzSettingsDB.preferences.graphicsPreset==importedBundle.preferences.graphicsPreset and _G.STierBlizzSettingsDB.profiles[saved.id]~=nil and ns.__widgetEnabled==importedBundle.preferences.performanceWidgetEnabled);_G.__combat=true;check("full addon import is blocked in combat",ns:ApplyAddonBundle(importedBundle).code=="combat");_G.__combat=false;ns.SetPerformanceWidgetEnabled=oldWidgetSetter
local blankSaved,blankWhy=ns:SaveCurrent("   ",{graphics=true});check("whitespace-only profile names are rejected",not blankSaved and blankWhy=="name")
local escapedRaw=ns:Serialize({value="line\ncontrol\0end"});local escapedParsed=ns:ParseSerialized(escapedRaw);check("serializer roundtrips escaped control bytes",escapedParsed and escapedParsed.value=="line\ncontrol\0end")
local duplicate,duplicateWhy=ns:ParseSerialized('{["a"]="1",["a"]="2",}');check("parser rejects duplicate keys",not duplicate and duplicateWhy=="duplicate")
local graphicsOnly=ns:SaveCurrent("Graphics only",{graphics=true});check("graphics-only save omits interface",next(graphicsOnly.sections.camera)==nil);local interfaceOnly=ns:SaveCurrent("Interface only",{interfaceGameplay=true});check("interface-only save omits graphics values",next(interfaceOnly.sections.graphics.base)==nil)
local function encodePayload(value) local raw=ns:Serialize(value);return ns.EXPORT_PREFIX..ns:Checksum(raw)..":"..ns:Base64Encode(raw)end
local function encodedWith(modules) return encodePayload({exportVersion=ns.EXPORT_VERSION,profileSchemaVersion=ns.PROFILE_SCHEMA,gameFlavor="retail",selectedModules=modules,profile=saved})end
for _,bad in ipairs({{}, {graphics=true}, {graphics=true,interfaceGameplay="yes"}, {graphics=true,interfaceGameplay=false,other=true}})do check("invalid selectedModules rejected",not ns:ImportProfile(encodedWith(bad)))end
local hostile=ns:Copy(saved);hostile.sections.graphics.base="not-a-table";local hostileText=encodePayload({exportVersion=ns.EXPORT_VERSION,profileSchemaVersion=ns.PROFILE_SCHEMA,gameFlavor="retail",selectedModules={graphics=true,interfaceGameplay=false},profile=hostile});local hostileOk,hostilePayload=pcall(ns.ImportProfile,ns,hostileText);check("structurally hostile profile fails closed without throwing",hostileOk and not hostilePayload)
local legacy=ns:Copy(saved);legacy.schemaVersion=nil;local migratedLegacy=ns:MigrateProfile(legacy);check("legacy profile migration restores current schema",migratedLegacy and migratedLegacy.schemaVersion==ns.PROFILE_SCHEMA);local future=ns:Copy(saved);future.schemaVersion=ns.PROFILE_SCHEMA+1;check("future profile migration is rejected",not ns:MigrateProfile(future))
local badName=ns:Copy(saved);badName.displayName="spoof\nname";local badNameText=encodePayload({exportVersion=ns.EXPORT_VERSION,profileSchemaVersion=ns.PROFILE_SCHEMA,gameFlavor="retail",selectedModules={graphics=true,interfaceGameplay=false},profile=badName});check("profile metadata control characters rejected",not ns:ImportProfile(badNameText))
local missingMode=ns:Copy(saved);missingMode.sections.graphics.mode=nil;local missingModeText=encodePayload({exportVersion=ns.EXPORT_VERSION,profileSchemaVersion=ns.PROFILE_SCHEMA,gameFlavor="retail",selectedModules={graphics=true,interfaceGameplay=false},profile=missingMode});check("graphics profile without explicit mode rejected",not ns:ImportProfile(missingModeText))
check("display text escapes WoW markup",ns:SafeText("|cff00ff00name|r")=="||cff00ff00name||r")
local fpsMetric=ns:CalculateFPSMetric({70,78},{90,92});check("FPS metric calculates averages and gain",fpsMetric and fpsMetric.before==74 and fpsMetric.after==91 and fpsMetric.delta==17);check("FPS metric formats a concise result",ns:FormatFPSMetric(fpsMetric):find("74") and ns:FormatFPSMetric(fpsMetric):find("91") and not ns:FormatFPSMetric(fpsMetric):find("→"))
local smoothTimes,stutterTimes={},{};for i=1,100 do smoothTimes[i]=1/100;stutterTimes[i]=i==1 and 0.06 or 1/100 end;local smoothStats=ns:FrametimeStats(smoothTimes);local stutterStats=ns:FrametimeStats(stutterTimes);check("accurate benchmark derives 1% Low from worst frame times",smoothStats.onePercentLow==100 and math.floor(stutterStats.onePercentLow+0.5)==17 and stutterStats.average<100);check("standalone FPS analysis reports stability, spikes and worst frame",smoothStats.stability==100 and smoothStats.spikes==0 and stutterStats.stability<100 and stutterStats.spikes==1 and math.floor(stutterStats.worstFrameMs+0.5)==60)
local oldCaptureFrameTimes=ns.CaptureFrameTimes;local capturedDuration,capturedPhase,standaloneResult;ns.CaptureFrameTimes=function(_,duration,phase,callback)capturedDuration,capturedPhase=duration,phase;callback(smoothTimes);return true end;check("standalone FPS test runs one 20-second frame-time capture",ns:StartStandaloneFPSTest(function(result)standaloneResult=result end) and capturedDuration==20 and capturedPhase=="standalone" and standaloneResult and standaloneResult.onePercentLow==100 and ns:GetLastStandaloneFPSTest()==standaloneResult);ns.CaptureFrameTimes=oldCaptureFrameTimes
local comparisonResult,comparisonRestore,comparisonPhases,comparisonDurations;comparisonPhases,comparisonDurations={},{};local originalShadow=store.graphicsShadowQuality;local beforeComparisonBackups=#_G.STierBlizzSettingsDB.backups;ns.CaptureFrameTimes=function(_,duration,phase,callback)table.insert(comparisonPhases,phase);table.insert(comparisonDurations,duration);local samples={};for i=1,100 do samples[i]=phase=="comparison-current" and 1/50 or 1/80 end;callback(samples);return true end;check("preset FPS comparison measures current and candidate graphics then restores the original",ns:StartPresetFPSComparison(ns.GRAPHICS_PRESET_PRO,function(metric,restored)comparisonResult,comparisonRestore=metric,restored end) and comparisonPhases[1]=="comparison-current" and comparisonPhases[2]=="comparison-preset" and comparisonDurations[1]==20 and comparisonDurations[2]==20 and comparisonResult and math.floor(comparisonResult.before+0.5)==50 and math.floor(comparisonResult.after+0.5)==80 and comparisonRestore and comparisonRestore.ok and store.graphicsShadowQuality==originalShadow and ns:GetLastPresetFPSComparison()==comparisonResult);check("preset comparison keeps one rollback backup and discards its temporary restore backup",#_G.STierBlizzSettingsDB.backups>=math.min(beforeComparisonBackups+1,_G.STierBlizzSettingsDB.preferences.backupLimit) and _G.STierBlizzSettingsDB.backups[1].trigger=="fps-compare-"..ns.GRAPHICS_PRESET_PRO);ns.CaptureFrameTimes=function()return true end;check("running FPS test can be cancelled cleanly",ns:StartStandaloneFPSTest() and ns:CancelFPSTest().code=="cancelled" and not ns.fpsTestMeasurement and not ns.fpsTestRun);ns.CaptureFrameTimes=oldCaptureFrameTimes
local liveFPS;ns:SetLiveFPSCallback(function(value)liveFPS=value end);check("live FPS callback receives current framerate",liveFPS==60);ns:SetLiveFPSCallback(nil)
store.graphicsShadowQuality="1";store.cameraSmoothStyle="1";local initial=ns:CreateBackup({graphics=true,interfaceGameplay=true},"test");local beforeRestore=#_G.STierBlizzSettingsDB.backups;store.graphicsShadowQuality="5";store.cameraSmoothStyle="4";local restore=ns:RestoreBackup(1,{graphics=true,interfaceGameplay=true});check("full restore succeeds",restore.ok and store.graphicsShadowQuality=="1" and store.cameraSmoothStyle=="1");check("restore creates one safety backup",#_G.STierBlizzSettingsDB.backups==beforeRestore+1)
store.graphicsShadowQuality="5";store.cameraSmoothStyle="4";local graphicsRestore=ns:RestoreBackup(2,{graphics=true});check("graphics-only restore",graphicsRestore.ok and store.graphicsShadowQuality=="1" and store.cameraSmoothStyle=="4");store.graphicsShadowQuality="5";store.cameraSmoothStyle="4";local interfaceRestore=ns:RestoreBackup(3,{interfaceGameplay=true});check("interface-only restore",interfaceRestore.ok and store.graphicsShadowQuality=="5" and store.cameraSmoothStyle=="1")
_G.STierBlizzSettingsDB={preferences="bad",profiles="bad",backups="bad",log="bad",transactions="bad"};local db=ns:InitializeDatabase();check("corrupted SavedVariables recovered",type(db.preferences)=="table" and type(db.profiles)=="table" and type(db.backups)=="table")
_G.__combat=true;local queued=ns:ApplySettings({cameraSmoothStyle="0"},{interfaceGameplay=true},"test");check("combat queue created",queued.code=="queued" and ns.pending~=nil);check("pending cancellation",ns:CancelPendingOperation().ok and ns.pending==nil);_G.__combat=false
_G.__combat=true;local invalidQueued=ns:ApplySettings({unknownSetting="1"},{interfaceGameplay=true},"bad");check("invalid operation is rejected before combat queue",invalidQueued.code~="queued" and ns.pending==nil);_G.__combat=false
check("transaction rejects settings outside selected modules",ns:ApplySettings({cameraSmoothStyle="0"},{graphics=true},"wrong-module").code=="no-settings")
store.graphicsDepthEffects="0";store.graphicsLiquidDetail="0";local originalSetCVar=_G.C_CVar.SetCVar;_G.C_CVar.SetCVar=function(key,value)if key=="graphicsLiquidDetail" then return false end;store[key]=value;return true end;local atomic=ns:ApplySettings({graphicsDepthEffects="3",graphicsLiquidDetail="3"},{graphics=true},"atomic-test");check("failed transaction reports rollback",not atomic.ok and atomic.code=="rolled-back" and atomic.data.rollback.failed==0);check("failed transaction restores earlier writes",store.graphicsDepthEffects=="0" and store.graphicsLiquidDetail=="0");_G.C_CVar.SetCVar=originalSetCVar
check("malformed imports never throw",pcall(function()return ns:ImportProfile("STBS1:not-valid")end));check("oversized import rejected",not ns:ImportProfile("STBS1:"..string.rep("a",ns.MAX_IMPORT_BYTES)))
local staleBackup={timestamp=100,affectedModules={interfaceGameplay=true},values={unknownOldSetting="1",cameraSmoothStyle="1"},readFailures={}};table.insert(_G.STierBlizzSettingsDB.backups,1,staleBackup);store.cameraSmoothStyle="0";local staleRestore=ns:RestoreBackup(1,{interfaceGameplay=true});check("restore ignores removed registry keys and restores known settings",staleRestore.ok and store.cameraSmoothStyle=="1")
local zeroBackup={timestamp=100,affectedModules={graphics=true},values={graphicsProjectedTextures="0",graphicsParticleDensity="0",graphicsOutlineMode="0"},readFailures={}};table.insert(_G.STierBlizzSettingsDB.backups,1,zeroBackup);store.graphicsProjectedTextures="1";store.graphicsParticleDensity="4";store.graphicsOutlineMode="2";local zeroRestore=ns:RestoreBackup(1,{graphics=true});check("backup restore can return values below official safety minimum",zeroRestore.ok and store.graphicsProjectedTextures=="0" and store.graphicsParticleDensity=="0" and store.graphicsOutlineMode=="0")
local deletable=ns:CreateBackup({graphics=true},"delete-test");local beforeDelete=#_G.STierBlizzSettingsDB.backups;check("backup deletion succeeds",deletable.ok and ns:DeleteBackup(1).ok and #_G.STierBlizzSettingsDB.backups==beforeDelete-1);check("invalid backup deletion fails closed",not ns:DeleteBackup(999).ok)
_G.STierBlizzSettingsDB.profiles.corrupt="bad";local safeList=ns:ListPersonalProfiles();check("corrupted personal profile entry is ignored",type(safeList)=="table")
assert(loadfile("STierBlizzSettings/UI/MainWindow.lua"))(addon,ns)
local mainWindowSourceFile=assert(io.open("STierBlizzSettings/UI/MainWindow.lua","rb"));local mainWindowSource=mainWindowSourceFile:read("*a");mainWindowSourceFile:close();check("main addon window can move beyond screen edges",mainWindowSource:find("f:SetClampedToScreen(false)",1,true)~=nil)
local styleSourceFile=assert(io.open("STierBlizzSettings/UI/Style.lua","rb"));local styleSource=styleSourceFile:read("*a");styleSourceFile:close();local blizzardSettingsSourceFile=assert(io.open("STierBlizzSettings/Integrations/BlizzardSettings.lua","rb"));local blizzardSettingsSource=blizzardSettingsSourceFile:read("*a");blizzardSettingsSourceFile:close();check("Retail button style uses scalable flat layers instead of stretched red templates",styleSource:find('edgeFile=WHITE',1,true)~=nil and styleSource:find('button.accent',1,true)~=nil and not styleSource:find("UIPanelButtonTemplate",1,true) and not mainWindowSource:find("UIPanelButtonTemplate",1,true) and not mainWindowSource:find("PanelTabButtonTemplate",1,true) and not blizzardSettingsSource:find("UIPanelButtonTemplate",1,true));check("button hover animation keeps its final alpha smoothly",styleSource:find("hoverIn:SetToFinalAlpha(true)",1,true)~=nil and styleSource:find("hoverOut:SetToFinalAlpha(true)",1,true)~=nil);check("checkboxes share the scalable button visual system",styleSource:find("CreateModernCheckBox",1,true)~=nil and styleSource:find("checkbox.checkedFill",1,true)~=nil and mainWindowSource:find("STBS:CreateModernCheckBox",1,true)~=nil and not mainWindowSource:find("UICheckButtonTemplate",1,true))
check("main addon window opens at the exact screen center",mainWindowSource:find('f:SetPoint("CENTER",UIParent,"CENTER",0,0)',1,true)~=nil)
check("Graphics sub-tabs use a dedicated top bar above the page title",mainWindowSource:find('f.graphicsTabBar:SetPoint("TOPLEFT",panel,"TOPLEFT",22,-10)',1,true)~=nil and mainWindowSource:find('f.header:SetPoint("TOPLEFT",22,-55)',1,true)~=nil and mainWindowSource:find('f.zoneGraphicsTab:SetPoint("TOPLEFT",f.graphicsSettingsTab,"TOPRIGHT",8,0)',1,true)~=nil)
check("redundant view-in-game action is absent",not mainWindowSource:find("ViewInGame",1,true) and ns.Locale.enUS.VIEW_IN_GAME==nil)
check("multiline import and export sheet has no single-line input template",not mainWindowSource:find("InputBoxTemplate",1,true))
check("FPS progress keeps its gold color and animates with a soft native fill",mainWindowSource:find("SetStatusBarColor(0.78,0.52,0.08)",1,true)~=nil and mainWindowSource:find('SetScript("OnUpdate",updateSmoothProgress)',1,true)~=nil and mainWindowSource:find("Raid-Bar-Hp-Fill",1,true)~=nil and mainWindowSource:find("UI-CastingBar-Spark",1,true)~=nil)
check("FPS modal warning is concise and forbids minimizing or Alt-Tab",ns:L("FPS_TEST_MODAL_HELP"):find("Alt+Tab",1,true)~=nil and #ns:L("FPS_TEST_MODAL_HELP")<110)
check("header always refreshes the detected current preset",mainWindowSource:find("f.currentPreset",1,true)~=nil and mainWindowSource:find("RefreshCurrentPresetLabel",1,true)~=nil)
local selectedMode,pages=nil,{}
ns.CreateUI=function()end;ns.SetPage=function(_,title,text,actions,status,options)pages={title=title,text=text,actions=actions,status=status,options=options}end;ns.RegisterBlizzardSettings=function()return true end
for i=1,3 do local profile=ns:NewProfile("ui_profile_"..i,"personal","UI Profile "..i);profile.sections.graphics={mode=ns.GRAPHICS_MODE_UNIFIED,base={},raid={}};profile.capturedModules={graphics=true};_G.STierBlizzSettingsDB.profiles[profile.id]=profile end;ns:ShowProfiles();check("combined profile page exposes profiles and backups",#pages.actions>=10 and pages.options.pageKey=="profiles")
selectedMode=ns.GRAPHICS_MODE_SPLIT;ns.GetSelectedMode=function()return selectedMode end;ns.SetSelectedMode=function(_,mode)selectedMode=mode;return true end;ns.pending=nil;ns:ShowHome();check("home opens the simple graphics preset experience",pages.options.pageKey=="graphics" and pages.options.graphicsSection=="settings" and pages.actions[2].active and #pages.actions>=7);pages.actions[1].fn();check("graphics preset selection stays on graphics",ns:GetSelectedPreset()==ns.GRAPHICS_PRESET_PRO and pages.options.pageKey=="graphics");pages.actions[5].fn();check("apply action opens a reviewed graphics preview",pages.title==ns:L("PREVIEW"))
local graphicsDashboard=ns:BuildGraphicsFPSDashboard({before=117,after=136,delta=19,percent=16},137,false);check("Graphics uses four visual FPS result cards",#graphicsDashboard==4 and graphicsDashboard[1].value=="137 FPS" and graphicsDashboard[2].value=="117 FPS" and graphicsDashboard[3].value=="136 FPS" and graphicsDashboard[4].value=="+19 FPS" and graphicsDashboard[4].subtitle=="+16%");local measuringDashboard=ns:BuildGraphicsFPSDashboard({before=117,after=136,delta=19,percent=16},137,true);check("Graphics hides stale before-after results while measuring",measuringDashboard[2].value=="—" and measuringDashboard[3].value=="—" and measuringDashboard[4].value=="—")
_G.IsInInstance=function()return true,"raid"end;check("zone graphics maps current Retail instance type",ns:GetZoneCategory()=="raid");ns:ShowZoneGraphics();check("zone graphics is nested under Graphics and remains opt-in",pages.options.pageKey=="graphics" and pages.options.graphicsSection=="zones" and pages.actions[1].kind=="check" and pages.actions[1].label==ns:L("ZONE_CHECK"))
_G.C_PartyInfo={IsDelveInProgress=function()return true end};check("active Delve uses the scenario mapping",ns:GetZoneCategory()=="scenario");_G.C_PartyInfo=nil
_G.GetNetStats=function()return 0,0,35,82 end;local snapshot=ns:GetPerformanceSnapshot();check("performance widget uses real FPS and higher Home/World latency",snapshot.fps==60 and snapshot.home==35 and snapshot.world==82 and snapshot.ping==82)
ns:SetZoneGraphicsEnabled(true);ns:GetZoneGraphicsConfig().assignments.raid=ns.GRAPHICS_PRESET_PRO;store.graphicsShadowQuality="5";local beforeZoneBackups=#_G.STierBlizzSettingsDB.backups;local zoneApply=ns:ApplyZoneGraphics("test-zone");check("zone graphics applies through a backup-first transaction",zoneApply.ok and store.graphicsShadowQuality=="1" and #_G.STierBlizzSettingsDB.backups==beforeZoneBackups+1)
local oldShowCopyBox=ns.ShowCopyBox;local importBoxText,importBoxSelectAll;ns.ShowCopyBox=function(_,text,selectAll)importBoxText,importBoxSelectAll=text,selectAll end;ns:OpenAddonImport();check("full settings import uses a large in-page text box",pages.title==ns:L("IMPORT_ALL") and pages.actions[1].label==ns:L("IMPORT_REVIEW") and importBoxText=="" and importBoxSelectAll==false);ns.ShowCopyBox=oldShowCopyBox
local oldComparisonGetter=ns.GetLastPresetFPSComparison;ns.GetLastPresetFPSComparison=function()return nil end;ns:ShowFPSTest();check("standalone FPS dashboard keeps its explained result",not pages.options.fpsComparison and pages.text:find(ns:L("FPS_TEST_STABILITY_EXPLAIN"):sub(1,9),1,true));ns.GetLastPresetFPSComparison=oldComparisonGetter
ns:ShowFPSTest();check("FPS test dashboard offers standalone and three preset comparisons",pages.options.pageKey=="fpsTest" and #pages.options.fpsDashboard==4 and pages.actions[1].label==ns:L("FPS_TEST_START") and pages.actions[2].label:find(ns:L("PRESET_PRO"),1,true) and pages.actions[5].kind=="check" and pages.actions[5].label==ns:L("WIDGET_CHECK"));check("preset result uses visual comparison cards with signed deltas",pages.options.fpsComparison and pages.options.fpsDashboard[1].label==ns:L("FPS_COMPARE_DASH_PRESET") and pages.options.fpsDashboard[2].subtitle:find("+30 FPS",1,true));check("preset comparison labels left as personal and right as tested preset",pages.options.fpsLegend and pages.options.fpsLegend:find(ns:L("PRESET_PRO"),1,true));check("preset comparison replaces diagnostic paragraphs with a concise restore note",pages.text:find(ns:L("FPS_COMPARE_DASH_HELP"),1,true) and pages.text:find(ns:L("FPS_COMPARE_RESTORED"),1,true) and not pages.text:find(ns:L("FPS_TEST_STABILITY_EXPLAIN"):sub(1,9),1,true) and not pages.text:find(string.format(ns:L("FPS_COMPARE_RESULT_TITLE"),ns:L("PRESET_PRO")),1,true))
ns.uiTweaksDraft=nil;ns:ShowUITweaks();check("UI Tweaks page exposes recommended and optional controls",pages.options.pageKey=="uiTweaks" and pages.actions[1].kind=="section" and pages.actions[2].kind=="check" and pages.actions[4].kind=="slider" and pages.actions[7].kind=="check" and pages.text:find(ns:L("UI_TWEAKS_TRUST"),1,true));ns:SelectRecommendedUITweaks();local tweakSettings=ns:GetAvailableUITweakSettings();local beforeTweakBackups=#_G.STierBlizzSettingsDB.backups;local tweakApply=ns:ApplySettings(tweakSettings,{uiTweaks=true},"ui-tweaks-test");check("UI Tweaks apply transactionally with a backup",tweakApply.ok and tweakApply.data.uiTweaks and #_G.STierBlizzSettingsDB.backups==beforeTweakBackups+1 and store.ResampleAlwaysSharpen=="1" and ns:SettingValuesEqual(ns.RegistryByKey.ResampleSharpness,store.ResampleSharpness,"0.3") and store.ffxGlow=="1")
ns:ShowAbout();check("about page explains the addon trust model",pages.options.pageKey=="about" and pages.text:find(ns:L("ABOUT_TRUST_HEADER"),1,true))
print((failed==0 and "PASS" or "FAIL")..": "..passed.." passed, "..failed.." failed");os.exit(failed==0 and 0 or 1)
