-- Pure Lua unit tests; run with `lua Tests/run.lua` from the repository root.
local passed, failed = 0, 0
local function check(name, condition) if condition then passed=passed+1 else failed=failed+1; io.stderr:write("FAIL: "..name.."\n") end end
_G.WOW_PROJECT_ID = 1; _G.WOW_PROJECT_MAINLINE = 1; _G.GetLocale=function() return "enUS" end; _G.time=function() return 1 end; _G.date=function() return "2026-07-14" end
local store={RAIDsettingsEnabled="0",graphicsProjectedTextures="1",graphicsParticleDensity="4",graphicsOutlineMode="2",graphicsSpellDensity="2",cameraSmoothStyle="1"}
_G.C_CVar={GetCVar=function(k)return store[k] end,GetCVarInfo=function(k) if store[k] then return store[k],store[k],false,false,false,false,false end end,SetCVar=function(k,v)store[k]=v;return true end};_G.C_VideoOptions={IsSpellVisualDensitySystemSupported=function()return true end};_G.GetBuildInfo=function()return "12.0.7","68453","",120007 end
local addon="STierBlizzSettings"; local ns={}; local files={"Core/Constants.lua","Localization/enUS.lua","Localization/ruRU.lua","Core/Bootstrap.lua","Core/Compatibility.lua","Core/Database.lua","Settings/Registry.lua","Settings/Validator.lua","Settings/Reader.lua","Settings/Writer.lua","Settings/Diff.lua","Settings/Backup.lua","Profiles/Schema.lua","Profiles/Migration.lua","Profiles/Recommended.lua","Profiles/Manager.lua","ImportExport/Serializer.lua","ImportExport/Codec.lua","ImportExport/Validation.lua","Settings/Transaction.lua"};for _,f in ipairs(files) do assert(loadfile("STierBlizzSettings/"..f))(addon,ns) end
ns:InitializeDatabase(); check("registry has verified settings",#ns.Registry>=30);check("valid cvar value",ns:ValidateValue(ns.RegistryByKey.graphicsProjectedTextures,"1"));check("reject unsafe projected textures",not ns:ValidateSettings({graphicsProjectedTextures="0"},true));check("unified profile",ns:GetOfficialGraphics("unified").sections.graphics.raid==nil);check("split profile",ns:GetOfficialGraphics("split").sections.graphics.raid.raidGraphicsProjectedTextures=="1")
ns:SetSelectedMode("unified");local a=ns:FlattenProfile(ns:GetOfficialGraphics("unified"),{graphics=true});check("unified disables raid",a.RAIDsettingsEnabled=="0");ns:SetSelectedMode("split");local b=ns:FlattenProfile(ns:GetOfficialGraphics("split"),{graphics=true});check("split enables raid",b.RAIDsettingsEnabled=="1")
local profile=ns:GetOfficialGraphics("split");local raw=ns:Serialize({profile=profile});check("codec roundtrip",ns:Base64Decode(ns:Base64Encode(raw))==raw);local one=ns:ExportProfile(profile,{graphics=true});local two=ns:ExportProfile(profile,{graphics=true});check("deterministic export",one==two);local payload,importReason=ns:ImportProfile(one);check("safe import",payload and payload.profile.id==profile.id);if not payload then io.stderr:write("Import reason: "..tostring(importReason).."\n") end;check("malformed rejected",not ns:ImportProfile("STBS1:bad"));check("oversize rejected",not ns:ImportProfile("STBS1:"..string.rep("a",ns.MAX_IMPORT_BYTES)))
local unsafe=ns:Copy(profile);unsafe.sections.graphics.base.notARealCVar="1";check("unknown fields rejected",not ns:ValidateProfile(unsafe));unsafe.sections.graphics.base.notARealCVar=nil;unsafe.sections.graphics.base.graphicsProjectedTextures="0";check("invalid profile values rejected",not ns:ValidateProfile(unsafe))
local backup=ns:CreateBackup({graphics=true},"test");check("backup plan",backup.ok and backup.data.values.graphicsProjectedTextures=="1");local diff=ns:BuildDiff({graphicsProjectedTextures="1",cameraSmoothStyle="0"});check("diff generation",#diff==2);local old={schemaVersion=1,sections={graphics={}}};check("migration",ns:MigrateProfile(old)~=nil);local future={schemaVersion=999,sections={}};check("future schema rejected",ns:MigrateProfile(future)==nil)
print((failed==0 and "PASS" or "FAIL")..": "..passed.." passed, "..failed.." failed");os.exit(failed==0 and 0 or 1)
