-- Pure Lua 5.1 regression tests. Run: lua Tests/run.lua
local passed, failed = 0, 0
local function check(name, condition) if condition then passed=passed+1 else failed=failed+1; io.stderr:write("FAIL: "..name.."\n") end end
local function equals(a,b) return a == b end
_G.WOW_PROJECT_ID=1; _G.WOW_PROJECT_MAINLINE=1; _G.GetLocale=function()return "enUS"end; _G.time=function()return 100 end; _G.date=function()return "2026-07-15"end; _G.InCombatLockdown=function()return _G.__combat or false end
local store={}; _G.C_CVar={GetCVar=function(k)return store[k] end,GetCVarInfo=function(k)if store[k]~=nil then return store[k],store[k],false,false,false,false,false end end,SetCVar=function(k,v)store[k]=v;return true end};_G.C_VideoOptions={IsSpellVisualDensitySystemSupported=function()return true end};_G.GetBuildInfo=function()return "12.0.7","68453","",120007 end
local addon,ns="STierBlizzSettings",{}
local files={"Core/Constants.lua","Localization/enUS.lua","Localization/ruRU.lua","Core/Bootstrap.lua","Core/Compatibility.lua","Core/Database.lua","Settings/Registry.lua","Settings/Validator.lua","Settings/Reader.lua","Settings/Writer.lua","Settings/Diff.lua","Settings/Backup.lua","Profiles/Schema.lua","Profiles/Migration.lua","Profiles/Recommended.lua","Profiles/Manager.lua","ImportExport/Serializer.lua","ImportExport/Codec.lua","ImportExport/Validation.lua","Settings/Transaction.lua"}
for _,f in ipairs(files)do assert(loadfile("STierBlizzSettings/"..f))(addon,ns)end
for _,setting in ipairs(ns.Registry)do local chosen=nil;for value in pairs(setting.validValues)do if not chosen or tonumber(value)<tonumber(chosen) then chosen=value end end;if setting.minimum then chosen=tostring(setting.minimum) end;store[setting.key]=chosen end
ns:InitializeDatabase()
check("registry contains base and raid settings",#ns.Registry>=32 and ns.RegistryByKey.graphicsShadowQuality~=nil and ns.RegistryByKey.raidGraphicsShadowQuality~=nil)
check("shadow quality accepts 5",ns:ValidateValue(ns.RegistryByKey.graphicsShadowQuality,"5"));check("shadow quality rejects 6",not ns:ValidateValue(ns.RegistryByKey.graphicsShadowQuality,"6"));check("liquid detail rejects 4",not ns:ValidateValue(ns.RegistryByKey.graphicsLiquidDetail,"4"));check("camera excludes 3",not ns:ValidateValue(ns.RegistryByKey.cameraSmoothStyle,"3"));check("texture filtering accepts 0",ns:ValidateValue(ns.RegistryByKey.textureFilteringMode,"0"))
for _,setting in ipairs(ns.Registry)do for value in pairs(setting.validValues)do if not setting.minimum or tonumber(value)>=setting.minimum then check("registry valid "..setting.key.."="..value,ns:ValidateValue(setting,value))end end end
check("unsafe base projected textures rejected",not ns:ValidateSettings({graphicsProjectedTextures="0"},true));check("unsafe raid projected textures rejected",not ns:ValidateSettings({graphicsProjectedTextures="1",raidGraphicsProjectedTextures="0"},true));check("unsafe base particle rejected",not ns:ValidateSettings({graphicsParticleDensity="0"},true));check("unsafe raid outline rejected",not ns:ValidateSettings({raidGraphicsOutlineMode="0"},true))
ns:SetSelectedMode("unified");check("invalid graphics mode rejected",not ns:SetSelectedMode("invalid"));local unified=ns:FlattenProfile(ns:GetOfficialGraphics("unified"),{graphics=true});check("unified disables raid",unified.RAIDsettingsEnabled=="0");local split=ns:FlattenProfile(ns:GetOfficialGraphics("split"),{graphics=true});check("split includes raid",split.RAIDsettingsEnabled=="1" and split.raidGraphicsProjectedTextures=="1")
_G.AntiAliasingSupported=function()return true,true,true end;check("AA prefers CMAA2",ns:GetPreferredAntiAliasing().ffxAntiAliasingMode=="4");_G.AntiAliasingSupported=function()return true,true,false end;check("AA falls back CMAA",ns:GetPreferredAntiAliasing().ffxAntiAliasingMode=="3");_G.AntiAliasingSupported=function()return true,false,false end;check("AA falls back FXAA High",ns:GetPreferredAntiAliasing().ffxAntiAliasingMode=="2");_G.AntiAliasingSupported=nil;check("AA preserves when capability unavailable",ns:GetPreferredAntiAliasing()==nil)
store.graphicsShadowQuality="1";store.cameraSmoothStyle="1";local saved=ns:SaveCurrent("Round trip",{graphics=true,interfaceGameplay=true});local export=ns:ExportProfile(saved,{graphics=true,interfaceGameplay=true});local payload,why=ns:ImportProfile(export);check("complete save export import roundtrip",payload and payload.profile.id==saved.id);local plan,planned=ns:PlanImport(payload,{graphics=true,interfaceGameplay=false},"current");check("module-selective import plan",#plan>0 and planned.cameraSmoothStyle==nil);check("profile mode preservation",planned.RAIDsettingsEnabled=="0")
local graphicsOnly=ns:SaveCurrent("Graphics only",{graphics=true});check("graphics-only save omits interface",next(graphicsOnly.sections.camera)==nil);local interfaceOnly=ns:SaveCurrent("Interface only",{interfaceGameplay=true});check("interface-only save omits graphics values",next(interfaceOnly.sections.graphics.base)==nil)
local function encodedWith(modules) local raw=ns:Serialize({exportVersion=ns.EXPORT_VERSION,gameFlavor="retail",selectedModules=modules,profile=saved});return ns.EXPORT_PREFIX..ns:Checksum(raw)..":"..ns:Base64Encode(raw)end
for _,bad in ipairs({{}, {graphics=true}, {graphics=true,interfaceGameplay="yes"}, {graphics=true,interfaceGameplay=false,other=true}})do check("invalid selectedModules rejected",not ns:ImportProfile(encodedWith(bad)))end
store.graphicsShadowQuality="1";store.cameraSmoothStyle="1";local initial=ns:CreateBackup({graphics=true,interfaceGameplay=true},"test");store.graphicsShadowQuality="5";store.cameraSmoothStyle="4";local restore=ns:RestoreBackup(1,{graphics=true,interfaceGameplay=true});check("full restore succeeds",restore.ok and store.graphicsShadowQuality=="1" and store.cameraSmoothStyle=="1");check("restore creates one safety backup",#_G.STierBlizzSettingsDB.backups==2)
store.graphicsShadowQuality="5";store.cameraSmoothStyle="4";local graphicsRestore=ns:RestoreBackup(2,{graphics=true});check("graphics-only restore",graphicsRestore.ok and store.graphicsShadowQuality=="1" and store.cameraSmoothStyle=="4");store.graphicsShadowQuality="5";store.cameraSmoothStyle="4";local interfaceRestore=ns:RestoreBackup(3,{interfaceGameplay=true});check("interface-only restore",interfaceRestore.ok and store.graphicsShadowQuality=="5" and store.cameraSmoothStyle=="1")
_G.STierBlizzSettingsDB={preferences="bad",profiles="bad",backups="bad",log="bad",transactions="bad"};local db=ns:InitializeDatabase();check("corrupted SavedVariables recovered",type(db.preferences)=="table" and type(db.profiles)=="table" and type(db.backups)=="table")
_G.__combat=true;local queued=ns:ApplySettings({cameraSmoothStyle="0"},{interfaceGameplay=true},"test");check("combat queue created",queued.code=="queued" and ns.pending~=nil);check("pending cancellation",ns:CancelPendingOperation().ok and ns.pending==nil);_G.__combat=false
check("malformed imports never throw",pcall(function()return ns:ImportProfile("STBS1:not-valid")end));check("oversized import rejected",not ns:ImportProfile("STBS1:"..string.rep("a",ns.MAX_IMPORT_BYTES)))
print((failed==0 and "PASS" or "FAIL")..": "..passed.." passed, "..failed.." failed");os.exit(failed==0 and 0 or 1)
