local _, STBS = ...

local english={
  SHOW_CHANGES="Show changes",
  SHOW_CHANGES_TIP="Open the optional detailed view. Technical CVar names remain hidden from the normal view.",
  DETAILED_DIFF_TITLE="Detailed changes",
  DETAILED_DIFF_HELP="Only settings that need attention are shown. Already-matching settings stay hidden.",
  DETAILED_DIFF_CHANGED="Will change (%d)",
  DETAILED_DIFF_UNAVAILABLE="Unavailable on this client (%d)",
  DETAILED_DIFF_SKIPPED="Skipped safely (%d)",
  DETAILED_DIFF_FAILED="Invalid or failed validation (%d)",
  DETAILED_DIFF_EMPTY="Everything already matches.",
  DETAILED_DIFF_NO_WRITES="No writable changes. Review unavailable, skipped or invalid items below.",
  DIFF_CURRENT_TO_TARGET="Current: %s   |TInterface\\Buttons\\UI-SpellbookIcon-NextPage-Up:14:14|t   Target: %s",
  DIFF_VALUE_ENABLED="Enabled", DIFF_VALUE_DISABLED="Disabled", DIFF_VALUE_UNAVAILABLE="Unavailable", DIFF_VALUE_UNKNOWN="Unknown",
  DIFF_VALUE_LEVEL="Level %s", DIFF_VALUE_FACTOR="%.1fx", DIFF_VALUE_ESSENTIAL="Essential", DIFF_VALUE_REDUCED="Reduced", DIFF_VALUE_EVERYTHING="Everything", DIFF_VALUE_SEPARATE="Separate raid settings", DIFF_VALUE_UNIFIED="Same settings everywhere",
  DIFF_REASON_UNAVAILABLE="WoW does not expose this setting as safely writable on the current client.",
  DIFF_REASON_UNSUPPORTED="The requested value is not supported by this client or hardware.",
  DIFF_REASON_SKIPPED="This setting was safely skipped and will not be written.",
  DIFF_REASON_FAILED="The requested value did not pass validation and will not be written.",
  DIFF_SETTING_GENERIC="WoW setting", DIFF_SETTING_GRAPHICS="Graphics option", DIFF_SETTING_RAID="Raid graphics option", DIFF_SETTING_TWEAK="Visual tweak", DIFF_SETTING_CAMERA="Camera option", DIFF_SETTING_INTERFACE="Interface option", DIFF_SETTING_COMBAT="Combat readability option", DIFF_SETTING_NAMEPLATE="Nameplate option",
  DIFF_EXPLAIN_GENERIC="Adjusts a curated built-in WoW setting.",
  DIFF_EXPLAIN_RAID_MODE="Controls whether Blizzard keeps a separate graphics set for raids and battlegrounds.",
  DIFF_EXPLAIN_TEXTURE_FILTERING="Controls how clearly textures remain visible at an angle.",
  DIFF_EXPLAIN_SHADOWS="Balances shadow detail and ray-traced shadow cost.",
  DIFF_EXPLAIN_ANTIALIASING="Smooths jagged edges using a mode supported by the current client.",
  DIFF_EXPLAIN_CAMERA="Controls the built-in camera following behavior.",
  DIFF_EXPLAIN_INTERFACE="Improves clarity of built-in interface information.",
  DIFF_EXPLAIN_COMBAT="Keeps important combat targets and silhouettes easier to read.",
  DIFF_EXPLAIN_NAMEPLATES="Controls when built-in unit nameplates remain visible.",
  DIFF_EXPLAIN_LIQUID="Adjusts water detail and reflection cost.",
  DIFF_EXPLAIN_PARTICLES="Balances particle detail while preserving readable combat effects.",
  DIFF_EXPLAIN_LIGHTING="Adjusts ambient lighting and contact-shadow detail.",
  DIFF_EXPLAIN_EFFECTS="Balances depth and compute-based scene effects against performance.",
  DIFF_EXPLAIN_OUTLINES="Preserves readable outlines around characters and objects.",
  DIFF_EXPLAIN_TEXTURES="Controls texture resolution without changing display resolution or render scale.",
  DIFF_EXPLAIN_SPELLS="Controls how many spell visuals are shown while preserving essential effects.",
  DIFF_EXPLAIN_PROJECTED="Keeps important projected ground effects visible.",
  DIFF_EXPLAIN_DISTANCE="Controls how far world objects and terrain remain visible.",
  DIFF_EXPLAIN_ENVIRONMENT="Controls decorative environment detail around the player.",
  DIFF_EXPLAIN_CLUTTER="Controls decorative grass and small ground objects.",
}

local russian={
  SHOW_CHANGES="Показать изменения",
  SHOW_CHANGES_TIP="Открыть необязательный подробный просмотр. Технические имена CVar скрыты из обычного интерфейса.",
  DETAILED_DIFF_TITLE="Подробные изменения",
  DETAILED_DIFF_HELP="Показаны только настройки, требующие внимания. Уже совпадающие значения скрыты.",
  DETAILED_DIFF_CHANGED="Будут изменены (%d)",
  DETAILED_DIFF_UNAVAILABLE="Недоступны в этом клиенте (%d)",
  DETAILED_DIFF_SKIPPED="Безопасно пропущены (%d)",
  DETAILED_DIFF_FAILED="Не прошли проверку (%d)",
  DETAILED_DIFF_EMPTY="Все настройки уже совпадают.",
  DETAILED_DIFF_NO_WRITES="Нет доступных изменений. Ниже показаны недоступные, пропущенные или некорректные настройки.",
  DIFF_CURRENT_TO_TARGET="Сейчас: %s   |TInterface\\Buttons\\UI-SpellbookIcon-NextPage-Up:14:14|t   После: %s",
  DIFF_VALUE_ENABLED="Включено", DIFF_VALUE_DISABLED="Выключено", DIFF_VALUE_UNAVAILABLE="Недоступно", DIFF_VALUE_UNKNOWN="Неизвестно",
  DIFF_VALUE_LEVEL="Уровень %s", DIFF_VALUE_FACTOR="%.1fx", DIFF_VALUE_ESSENTIAL="Только важные", DIFF_VALUE_REDUCED="Снижено", DIFF_VALUE_EVERYTHING="Все эффекты", DIFF_VALUE_SEPARATE="Отдельно для рейдов", DIFF_VALUE_UNIFIED="Одинаково везде",
  DIFF_REASON_UNAVAILABLE="WoW не разрешает безопасно изменить эту настройку в текущем клиенте.",
  DIFF_REASON_UNSUPPORTED="Выбранное значение не поддерживается текущим клиентом или оборудованием.",
  DIFF_REASON_SKIPPED="Настройка безопасно пропущена и не будет записана.",
  DIFF_REASON_FAILED="Выбранное значение не прошло проверку и не будет записано.",
  DIFF_SETTING_GENERIC="Настройка WoW", DIFF_SETTING_GRAPHICS="Настройка графики", DIFF_SETTING_RAID="Графика для рейдов", DIFF_SETTING_TWEAK="Улучшение картинки", DIFF_SETTING_CAMERA="Настройка камеры", DIFF_SETTING_INTERFACE="Настройка интерфейса", DIFF_SETTING_COMBAT="Читаемость боя", DIFF_SETTING_NAMEPLATE="Настройка индикаторов",
  DIFF_EXPLAIN_GENERIC="Изменяет проверенную встроенную настройку WoW.",
  DIFF_EXPLAIN_RAID_MODE="Определяет, использует ли Blizzard отдельную графику для рейдов и полей боя.",
  DIFF_EXPLAIN_TEXTURE_FILTERING="Определяет чёткость текстур, расположенных под углом.",
  DIFF_EXPLAIN_SHADOWS="Балансирует детализацию теней и стоимость трассировки лучей.",
  DIFF_EXPLAIN_ANTIALIASING="Сглаживает неровные края поддерживаемым клиентом способом.",
  DIFF_EXPLAIN_CAMERA="Управляет стандартным поведением следования камеры.",
  DIFF_EXPLAIN_INTERFACE="Делает встроенную информацию интерфейса понятнее.",
  DIFF_EXPLAIN_COMBAT="Помогает лучше видеть важные цели и силуэты в бою.",
  DIFF_EXPLAIN_NAMEPLATES="Определяет, когда видны стандартные индикаторы существ.",
  DIFF_EXPLAIN_LIQUID="Меняет детализацию воды и стоимость отражений.",
  DIFF_EXPLAIN_PARTICLES="Балансирует частицы, сохраняя читаемые боевые эффекты.",
  DIFF_EXPLAIN_LIGHTING="Меняет фоновое освещение и контактные тени.",
  DIFF_EXPLAIN_EFFECTS="Балансирует эффекты глубины и вычисляемые эффекты сцены.",
  DIFF_EXPLAIN_OUTLINES="Сохраняет заметные контуры персонажей и объектов.",
  DIFF_EXPLAIN_TEXTURES="Меняет качество текстур, не затрагивая разрешение и масштаб рендера.",
  DIFF_EXPLAIN_SPELLS="Определяет количество эффектов заклинаний, сохраняя важные.",
  DIFF_EXPLAIN_PROJECTED="Сохраняет важные эффекты, отображаемые на земле.",
  DIFF_EXPLAIN_DISTANCE="Определяет дальность отображения объектов и ландшафта.",
  DIFF_EXPLAIN_ENVIRONMENT="Определяет количество декоративных деталей окружения.",
  DIFF_EXPLAIN_CLUTTER="Определяет количество травы и небольших объектов на земле.",
}

for _,values in pairs(STBS.Locale) do for key,value in pairs(english) do values[key]=value end end
for key,value in pairs(russian) do STBS.Locale.ruRU[key]=value end
