local _, STBS = ...
STBS.Locale = STBS.Locale or {}
STBS.Locale.enUS = {
  TITLE = "S-Tier Blizz Settings", HOME = "Home", GRAPHICS = "Graphics", INTERFACE = "Interface & Gameplay", PROFILES = "Profiles", BACKUPS = "Backup & Restore", DIAGNOSTICS = "Diagnostics",
  APPLY_GRAPHICS = "Apply Graphics", APPLY_INTERFACE = "Apply Interface & Gameplay", APPLY_ALL = "Apply Everything", PREVIEW = "Preview Changes", SAVE = "Save Current Settings", EXPORT = "Export", IMPORT = "Import", RESTORE = "Restore",
  UNIFIED = "One Profile Everywhere", SPLIT = "Optimized Raid Mode", MODE = "Graphics mode", MODE_UNSET = "Choose a graphics mode before applying.",
  HOME_TEXT = "Optimal built-in WoW settings. One click. No UI pack required.", GRAPHICS_TEXT = "Balanced graphics normally, with an optional lighter Blizzard raid and battleground profile.", INTERFACE_TEXT = "Only verified non-personal Blizzard settings are included. Accessibility, sound, keybindings and hardware settings are preserved.",
  APPLY_QUEUED = "Settings will be applied after combat ends.", APPLY_DONE = "Settings applied. Review the report below.", BACKUP_CREATED = "Backup created.", IMPORT_HELP = "Paste an STBS1 profile string. WoW cannot copy directly to your clipboard; use Select All and copy manually.", EXPORT_HELP = "Select All, then copy this text manually.", INVALID_IMPORT = "The profile is invalid or unsupported.", RELOAD = "Some changes may require Reload UI or a graphics restart.", UNSUPPORTED = "This feature is unavailable in this client.", EDITMODE_CONFIRM = "Edit Mode restore requires explicit confirmation and is not included automatically.", KEYBINDING_OPTIN = "Keybindings are an advanced opt-in feature and are never applied automatically.",
  REPORT_GRAPHICS = "GRAPHICS APPLIED", REPORT_INTERFACE = "INTERFACE & GAMEPLAY APPLIED", CHANGED = "Changed", IDENTICAL = "Already configured", SKIPPED = "Skipped", FAILED = "Failed", UNAVAILABLE = "Unavailable", PRESERVED = "Preserved", COPY = "Select All", CREATE_BACKUP = "Create Manual Backup", RESTORE_ALL = "Restore Everything", RESTORE_GRAPHICS = "Restore Graphics Only", RESTORE_INTERFACE = "Restore Interface & Gameplay Only",
  PERSONAL = "Personal profile", DEMO = "Demonstration profile — not affiliated with a real player.", DIAGNOSTIC_COPY = "Diagnostic report", MODE_MISMATCH = "Selected graphics mode differs from the Blizzard raid-profile state. Reapply the selected mode if desired.",
}
