local _, STBS = ...
STBS.Locale = STBS.Locale or {}
STBS.Locale.frFR = {
  TITLE="S-Tier Blizz Settings", HOME="Accueil", GRAPHICS="Graphismes", INTERFACE="Interface et jeu", PROFILES="Profils", BACKUPS="Sauvegarde et restauration", DIAGNOSTICS="Diagnostic",
  APPLY_GRAPHICS="Appliquer les graphismes", APPLY_INTERFACE="Appliquer l'interface et le jeu", APPLY_ALL="Tout appliquer", PREVIEW="Prévisualiser les modifications", SAVE="Enregistrer les réglages actuels", EXPORT="Exporter", IMPORT="Importer", RESTORE="Restaurer", COPY="Tout sélectionner",
  UNIFIED="Un seul profil partout", SPLIT="Mode raids optimisé", MODE="Mode graphique", MODE_UNSET="Choisissez un mode graphique avant d'appliquer les réglages.",
  HOME_TEXT="Réglages WoW intégrés optimaux. En un clic. Sans pack d'interface.", GRAPHICS_TEXT="Choisissez les mêmes graphismes partout, ou conservez un profil Blizzard plus léger pour les raids et les champs de bataille.", INTERFACE_TEXT="Le profil alpha officiel inclut une recommandation vérifiée et non personnelle : le style de suivi de la caméra « Ne jamais ajuster la caméra ».",
  CHANGED="Modifié", IDENTICAL="Déjà configuré", SKIPPED="Ignoré", FAILED="Échec", UNAVAILABLE="Indisponible", PRESERVED="Conservé", REPORT_GRAPHICS="GRAPHISMES APPLIQUÉS", REPORT_INTERFACE="INTERFACE ET JEU APPLIQUÉS",
  CREATE_BACKUP="Créer une sauvegarde manuelle", RESTORE_ALL="Tout restaurer", RESTORE_GRAPHICS="Restaurer uniquement les graphismes", RESTORE_INTERFACE="Restaurer l'interface et le jeu", BACKUP_CREATED="Sauvegarde créée.",
  SAVE_GRAPHICS="Enregistrer les graphismes", SAVE_INTERFACE="Enregistrer l'interface et le jeu", SAVE_ALL="Tout enregistrer", RENAME="Renommer", DELETE="Supprimer la sélection", SELECT="Sélectionner", CANCEL_PENDING="Annuler l'opération en attente", NO_PENDING="Aucune opération n'est en attente.",
  CONFIRM="Confirmer", BACK="Retour", IMPORT_GRAPHICS="Graphismes uniquement", IMPORT_INTERFACE="Interface et jeu uniquement", IMPORT_ALL="Tout", KEEP_MODE="Conserver le mode graphique actuel", USE_PROFILE_MODE="Utiliser le mode graphique du profil",
  PENDING="L'opération sera appliquée après la fin du combat.", IMPORT_HELP="Collez une chaîne de profil STBS1. WoW ne permet pas l'accès direct au presse-papiers ; utilisez « Tout sélectionner », puis copiez manuellement.", EXPORT_HELP="Utilisez « Tout sélectionner », puis copiez ce texte manuellement.", INVALID_IMPORT="Le profil est invalide ou n'est pas pris en charge.",
  PROFILE_NAME="Nom du profil :", IMPORT_PROMPT="Collez une chaîne de profil STBS1 :", SETTINGS_COUNT="réglages", IMPORT_CONFIRMATION="Choisissez ci-dessous l'étendue de l'importation pour confirmer. Aucune modification n'a encore été appliquée.", HARDWARE_PRESERVED="Réglages matériels conservés : écran, résolution, fréquence de rafraîchissement, V-Sync, limites d'IPS et mode de latence.", PERSONAL_PRESERVED="Réglages personnels conservés : échelle de l'interface, commandes de la souris, accessibilité, son et raccourcis clavier.",
  DIFF_HEADER="Aperçu des modifications", PROFILE_SUMMARY="Résumé du profil", BACKUP_HISTORY="Historique des sauvegardes", NO_BACKUPS="Aucune sauvegarde pour le moment.", NO_PROFILES="Aucun profil personnel enregistré.", SELECTED="Sélection", SIZE="Taille", BASE_GRAPHICS="Graphismes de base", RAID_GRAPHICS="Graphismes des raids et champs de bataille", CAMERA="Caméra", OTHER_INTERFACE="Interface et jeu", STATUS="État",
  PERSONAL="Profil personnel", UNSUPPORTED="Cette fonctionnalité n'est pas disponible dans ce client.", EDITMODE_UNAVAILABLE="La gestion des profils du mode Édition n'est pas disponible dans cette version alpha.", KEYBINDING_UNAVAILABLE="La gestion des profils de raccourcis clavier n'est pas disponible dans cette version alpha.", TRANSACTION_ROLLED_BACK="L'opération a été annulée, car un réglage n'a pas pu être vérifié.",
}
STBS.Locale.frFR.WELCOME="Pour configurer S-Tier Blizz Settings, tapez /stier ou cliquez sur le bouton de la minicarte."
STBS.Locale.frFR.MINIMAP_TOOLTIP="Cliquez avec le bouton gauche pour ouvrir les réglages."
