local _, STBS = ...

local strings = {
  enUS = {
    APPLY_AND_MEASURE="Apply and measure FPS", APPLY_CONFIRM="Apply graphics settings?", APPLY_CONFIRM_TEXT="Apply %d reviewed changes? A graphics backup will be created first.", SETTINGS_APPLIED="Graphics applied. Measuring FPS now…",
    FPS_RESULT_FORMAT="Average FPS: %d → %d, %+d FPS (%+d%%)", FPS_MEASURING="Measuring FPS… stay in the same place for 8 seconds.", FPS_MEASURE_HELP="FPS is measured locally before and after applying. The result is an estimate and depends on the scene, combat and background load.", FPS_UNAVAILABLE="FPS comparison is not available yet.", FPS_ESTIMATE="Local FPS estimate",
    VISUAL_PREVIEW="Balanced graphics preview", VISUAL_PREVIEW_NOTE="Illustrative preview: clear silhouettes, projected effects and restrained particles are preserved.", UNDO="Undo graphics changes", UNDO_CONFIRM="Restore previous graphics?", UNDO_CONFIRM_TEXT="Restore the latest graphics backup? A safety backup will be created first.", UNDO_UNAVAILABLE="No graphics backup is available yet.",
    PERSONAL_PROFILES="Personal profiles", BACKUPS_AND_PROFILES="Profiles & backups", CREATE_GRAPHICS_BACKUP="Create graphics backup", DELETE_BACKUP="Delete backup", DELETE_BACKUP_CONFIRM="Delete this backup permanently?", APPLY_PROFILE="Preview and apply profile", PROFILE_APPLY_CONFIRM="Apply personal profile?", PROFILE_APPLY_CONFIRM_TEXT="Apply the selected graphics profile? A backup will be created first.", GRAPHICS_ONLY_NOTICE="Interface & Gameplay is temporarily hidden while it is being redesigned.", RESTORE_SELECTED="Restore selected backup", BACKUP_LABEL="Backup", PROFILE_LABEL="Profile", RIGHT_CLICK_PROFILES="Right-click: profiles and backups", PENDING_FPS="The operation is queued until combat ends; FPS measurement will start afterwards.",
    MODE_UNIFIED_HELP="The same balanced graphics everywhere.", MODE_SPLIT_HELP="A lighter Blizzard raid and battleground profile.", MEASURED_LOCALLY="Measured on this character", SELECT_ITEM="Select an item below", NO_GRAPHICS_PROFILES="No graphics profiles saved yet.", RESTORE_COMPLETE="Graphics restored.", APPLY_FAILED="The operation could not be applied.",
  },
  ruRU = {
    APPLY_AND_MEASURE="Применить и измерить FPS", APPLY_CONFIRM="Применить настройки графики?", APPLY_CONFIRM_TEXT="Применить проверенные изменения (%d)? Сначала будет создана резервная копия графики.", SETTINGS_APPLIED="Графика применена. Измеряем FPS…",
    FPS_RESULT_FORMAT="Средний FPS: %d → %d, %+d FPS (%+d%%)", FPS_MEASURING="Измеряем FPS… оставайтесь на месте 8 секунд.", FPS_MEASURE_HELP="FPS измеряется локально до и после применения. Результат приблизительный и зависит от сцены, боя и фоновой нагрузки.", FPS_UNAVAILABLE="Сравнение FPS пока недоступно.", FPS_ESTIMATE="Локальная оценка FPS",
    VISUAL_PREVIEW="Превью сбалансированной графики", VISUAL_PREVIEW_NOTE="Иллюстративный пример: сохраняются чёткие силуэты, проецируемые эффекты и умеренные частицы.", UNDO="Вернуть назад", UNDO_CONFIRM="Вернуть предыдущую графику?", UNDO_CONFIRM_TEXT="Восстановить последнюю резервную копию графики? Сначала будет создана страховочная копия.", UNDO_UNAVAILABLE="Резервных копий графики пока нет.",
    PERSONAL_PROFILES="Личные профили", BACKUPS_AND_PROFILES="Профили и бэкапы", CREATE_GRAPHICS_BACKUP="Создать бэкап графики", DELETE_BACKUP="Удалить бэкап", DELETE_BACKUP_CONFIRM="Удалить этот бэкап безвозвратно?", APPLY_PROFILE="Проверить и применить профиль", PROFILE_APPLY_CONFIRM="Применить личный профиль?", PROFILE_APPLY_CONFIRM_TEXT="Применить выбранный профиль графики? Сначала будет создан бэкап.", GRAPHICS_ONLY_NOTICE="Раздел «Интерфейс и игра» временно скрыт на время переработки.", RESTORE_SELECTED="Восстановить выбранный бэкап", BACKUP_LABEL="Бэкап", PROFILE_LABEL="Профиль", RIGHT_CLICK_PROFILES="Правая кнопка: профили и бэкапы", PENDING_FPS="Операция выполнится после боя; затем начнётся измерение FPS.",
    MODE_UNIFIED_HELP="Одинаковая сбалансированная графика везде.", MODE_SPLIT_HELP="Облегчённый профиль Blizzard для рейдов и полей боя.", MEASURED_LOCALLY="Измерено на этом персонаже", SELECT_ITEM="Выберите элемент ниже", NO_GRAPHICS_PROFILES="Профили графики пока не сохранены.", RESTORE_COMPLETE="Графика восстановлена.", APPLY_FAILED="Не удалось применить настройки.",
  },
  frFR = {
    APPLY_AND_MEASURE="Appliquer et mesurer les IPS", APPLY_CONFIRM="Appliquer les graphismes ?", APPLY_CONFIRM_TEXT="Appliquer %d modifications vérifiées ? Une sauvegarde graphique sera créée.", SETTINGS_APPLIED="Graphismes appliqués. Mesure des IPS…", FPS_RESULT_FORMAT="IPS moyennes : %d → %d, %+d IPS (%+d%%)", FPS_MEASURING="Mesure des IPS… restez au même endroit pendant 8 secondes.", FPS_MEASURE_HELP="Mesure locale avant et après. Le résultat reste une estimation dépendant de la scène.", FPS_UNAVAILABLE="Comparaison des IPS indisponible.", FPS_ESTIMATE="Estimation locale des IPS", VISUAL_PREVIEW="Aperçu graphique équilibré", VISUAL_PREVIEW_NOTE="Aperçu illustratif : silhouettes, effets projetés et particules lisibles.", UNDO="Annuler les changements", UNDO_CONFIRM="Restaurer les graphismes précédents ?", UNDO_CONFIRM_TEXT="Restaurer la dernière sauvegarde graphique ? Une sauvegarde de sécurité sera créée.", UNDO_UNAVAILABLE="Aucune sauvegarde graphique disponible.", PERSONAL_PROFILES="Profils personnels", BACKUPS_AND_PROFILES="Profils et sauvegardes", CREATE_GRAPHICS_BACKUP="Créer une sauvegarde graphique", DELETE_BACKUP="Supprimer la sauvegarde", DELETE_BACKUP_CONFIRM="Supprimer définitivement cette sauvegarde ?", APPLY_PROFILE="Aperçu et application", PROFILE_APPLY_CONFIRM="Appliquer le profil personnel ?", PROFILE_APPLY_CONFIRM_TEXT="Appliquer le profil graphique sélectionné ?", GRAPHICS_ONLY_NOTICE="Interface et jeu est temporairement masqué pendant sa refonte.", RESTORE_SELECTED="Restaurer la sauvegarde", BACKUP_LABEL="Sauvegarde", PROFILE_LABEL="Profil", RIGHT_CLICK_PROFILES="Clic droit : profils et sauvegardes", PENDING_FPS="Opération en attente de la fin du combat ; mesure ensuite.", MODE_UNIFIED_HELP="Les mêmes graphismes équilibrés partout.", MODE_SPLIT_HELP="Profil Blizzard allégé pour raids et champs de bataille.", MEASURED_LOCALLY="Mesuré sur ce personnage", SELECT_ITEM="Sélectionnez un élément", NO_GRAPHICS_PROFILES="Aucun profil graphique enregistré.", RESTORE_COMPLETE="Graphismes restaurés.", APPLY_FAILED="Impossible d’appliquer les réglages.",
  },
  deDE = {
    APPLY_AND_MEASURE="Anwenden und FPS messen", APPLY_CONFIRM="Grafikeinstellungen anwenden?", APPLY_CONFIRM_TEXT="%d geprüfte Änderungen anwenden? Zuerst wird ein Grafik-Backup erstellt.", SETTINGS_APPLIED="Grafik angewendet. FPS werden gemessen…", FPS_RESULT_FORMAT="Durchschnittliche FPS: %d → %d, %+d FPS (%+d%%)", FPS_MEASURING="FPS-Messung… 8 Sekunden am selben Ort bleiben.", FPS_MEASURE_HELP="Lokale Vorher-Nachher-Messung; das Ergebnis ist eine szenenabhängige Schätzung.", FPS_UNAVAILABLE="Noch kein FPS-Vergleich verfügbar.", FPS_ESTIMATE="Lokale FPS-Schätzung", VISUAL_PREVIEW="Vorschau ausgewogener Grafik", VISUAL_PREVIEW_NOTE="Illustrative Vorschau mit klaren Silhouetten, Bodeneffekten und maßvollen Partikeln.", UNDO="Grafik zurücksetzen", UNDO_CONFIRM="Vorherige Grafik wiederherstellen?", UNDO_CONFIRM_TEXT="Letztes Grafik-Backup wiederherstellen? Zuerst wird ein Sicherheits-Backup erstellt.", UNDO_UNAVAILABLE="Kein Grafik-Backup verfügbar.", PERSONAL_PROFILES="Persönliche Profile", BACKUPS_AND_PROFILES="Profile & Backups", CREATE_GRAPHICS_BACKUP="Grafik-Backup erstellen", DELETE_BACKUP="Backup löschen", DELETE_BACKUP_CONFIRM="Dieses Backup dauerhaft löschen?", APPLY_PROFILE="Profil prüfen und anwenden", PROFILE_APPLY_CONFIRM="Persönliches Profil anwenden?", PROFILE_APPLY_CONFIRM_TEXT="Das gewählte Grafikprofil anwenden?", GRAPHICS_ONLY_NOTICE="Interface & Gameplay ist während der Überarbeitung vorübergehend ausgeblendet.", RESTORE_SELECTED="Gewähltes Backup wiederherstellen", BACKUP_LABEL="Backup", PROFILE_LABEL="Profil", RIGHT_CLICK_PROFILES="Rechtsklick: Profile und Backups", PENDING_FPS="Wird nach dem Kampf angewendet und anschließend gemessen.", MODE_UNIFIED_HELP="Überall dieselbe ausgewogene Grafik.", MODE_SPLIT_HELP="Leichteres Blizzard-Profil für Schlachtzüge und Schlachtfelder.", MEASURED_LOCALLY="Auf diesem Charakter gemessen", SELECT_ITEM="Element auswählen", NO_GRAPHICS_PROFILES="Noch keine Grafikprofile gespeichert.", RESTORE_COMPLETE="Grafik wiederhergestellt.", APPLY_FAILED="Einstellungen konnten nicht angewendet werden.",
  },
}

strings.esES = {
  APPLY_AND_MEASURE="Aplicar y medir FPS", APPLY_CONFIRM="¿Aplicar los gráficos?", APPLY_CONFIRM_TEXT="¿Aplicar %d cambios revisados? Primero se creará una copia de gráficos.", SETTINGS_APPLIED="Gráficos aplicados. Midiendo FPS…", FPS_RESULT_FORMAT="FPS medios: %d → %d, %+d FPS (%+d%%)", FPS_MEASURING="Midiendo FPS… permanece en el mismo lugar 8 segundos.", FPS_MEASURE_HELP="Medición local antes y después; el resultado es una estimación dependiente de la escena.", FPS_UNAVAILABLE="Aún no hay comparación de FPS.", FPS_ESTIMATE="Estimación local de FPS", VISUAL_PREVIEW="Vista previa equilibrada", VISUAL_PREVIEW_NOTE="Ejemplo ilustrativo con siluetas y efectos de suelo claros y partículas moderadas.", UNDO="Deshacer cambios", UNDO_CONFIRM="¿Restaurar los gráficos anteriores?", UNDO_CONFIRM_TEXT="¿Restaurar la última copia de gráficos? Se creará una copia de seguridad.", UNDO_UNAVAILABLE="No hay copias de gráficos.", PERSONAL_PROFILES="Perfiles personales", BACKUPS_AND_PROFILES="Perfiles y copias", CREATE_GRAPHICS_BACKUP="Crear copia de gráficos", DELETE_BACKUP="Eliminar copia", DELETE_BACKUP_CONFIRM="¿Eliminar esta copia permanentemente?", APPLY_PROFILE="Revisar y aplicar perfil", PROFILE_APPLY_CONFIRM="¿Aplicar perfil personal?", PROFILE_APPLY_CONFIRM_TEXT="¿Aplicar el perfil gráfico seleccionado?", GRAPHICS_ONLY_NOTICE="Interfaz y juego está oculto temporalmente durante su rediseño.", RESTORE_SELECTED="Restaurar copia seleccionada", BACKUP_LABEL="Copia", PROFILE_LABEL="Perfil", RIGHT_CLICK_PROFILES="Clic derecho: perfiles y copias", PENDING_FPS="Se aplicará al terminar el combate y se medirá después.", MODE_UNIFIED_HELP="Los mismos gráficos equilibrados en todas partes.", MODE_SPLIT_HELP="Perfil de Blizzard más ligero para bandas y campos de batalla.", MEASURED_LOCALLY="Medido en este personaje", SELECT_ITEM="Selecciona un elemento", NO_GRAPHICS_PROFILES="No hay perfiles gráficos guardados.", RESTORE_COMPLETE="Gráficos restaurados.", APPLY_FAILED="No se pudieron aplicar los ajustes.",
}
strings.esMX = strings.esES
strings.ptBR = {
  APPLY_AND_MEASURE="Aplicar e medir FPS", APPLY_CONFIRM="Aplicar gráficos?", APPLY_CONFIRM_TEXT="Aplicar %d alterações revisadas? Um backup gráfico será criado primeiro.", SETTINGS_APPLIED="Gráficos aplicados. Medindo FPS…", FPS_RESULT_FORMAT="FPS médio: %d → %d, %+d FPS (%+d%%)", FPS_MEASURING="Medindo FPS… fique no mesmo lugar por 8 segundos.", FPS_MEASURE_HELP="Medição local antes e depois; o resultado é uma estimativa dependente da cena.", FPS_UNAVAILABLE="Comparação de FPS ainda indisponível.", FPS_ESTIMATE="Estimativa local de FPS", VISUAL_PREVIEW="Prévia gráfica equilibrada", VISUAL_PREVIEW_NOTE="Exemplo ilustrativo com silhuetas e efeitos no chão claros e partículas moderadas.", UNDO="Desfazer gráficos", UNDO_CONFIRM="Restaurar gráficos anteriores?", UNDO_CONFIRM_TEXT="Restaurar o último backup gráfico? Um backup de segurança será criado.", UNDO_UNAVAILABLE="Nenhum backup gráfico disponível.", PERSONAL_PROFILES="Perfis pessoais", BACKUPS_AND_PROFILES="Perfis e backups", CREATE_GRAPHICS_BACKUP="Criar backup gráfico", DELETE_BACKUP="Excluir backup", DELETE_BACKUP_CONFIRM="Excluir este backup permanentemente?", APPLY_PROFILE="Revisar e aplicar perfil", PROFILE_APPLY_CONFIRM="Aplicar perfil pessoal?", PROFILE_APPLY_CONFIRM_TEXT="Aplicar o perfil gráfico selecionado?", GRAPHICS_ONLY_NOTICE="Interface e jogabilidade está oculto temporariamente durante a reformulação.", RESTORE_SELECTED="Restaurar backup selecionado", BACKUP_LABEL="Backup", PROFILE_LABEL="Perfil", RIGHT_CLICK_PROFILES="Clique direito: perfis e backups", PENDING_FPS="Será aplicado após o combate e medido em seguida.", MODE_UNIFIED_HELP="Os mesmos gráficos equilibrados em todos os lugares.", MODE_SPLIT_HELP="Perfil Blizzard mais leve para raides e campos de batalha.", MEASURED_LOCALLY="Medido neste personagem", SELECT_ITEM="Selecione um item", NO_GRAPHICS_PROFILES="Nenhum perfil gráfico salvo.", RESTORE_COMPLETE="Gráficos restaurados.", APPLY_FAILED="Não foi possível aplicar as configurações.",
}
strings.koKR = {
  APPLY_AND_MEASURE="적용 후 FPS 측정", APPLY_CONFIRM="그래픽 설정을 적용할까요?", APPLY_CONFIRM_TEXT="검토된 변경 %d개를 적용할까요? 먼저 그래픽 백업을 만듭니다.", SETTINGS_APPLIED="그래픽을 적용했습니다. FPS 측정 중…", FPS_RESULT_FORMAT="평균 FPS: %d → %d, %+d FPS (%+d%%)", FPS_MEASURING="FPS 측정 중… 8초 동안 같은 위치에 있으세요.", FPS_MEASURE_HELP="적용 전후를 로컬에서 측정한 장면별 추정치입니다.", FPS_UNAVAILABLE="아직 FPS 비교가 없습니다.", FPS_ESTIMATE="로컬 FPS 추정", VISUAL_PREVIEW="균형 그래픽 미리보기", VISUAL_PREVIEW_NOTE="선명한 윤곽, 바닥 효과와 적절한 입자를 보여 주는 예시입니다.", UNDO="그래픽 되돌리기", UNDO_CONFIRM="이전 그래픽을 복원할까요?", UNDO_CONFIRM_TEXT="최신 그래픽 백업을 복원할까요? 안전 백업을 먼저 만듭니다.", UNDO_UNAVAILABLE="사용 가능한 그래픽 백업이 없습니다.", PERSONAL_PROFILES="개인 프로필", BACKUPS_AND_PROFILES="프로필 및 백업", CREATE_GRAPHICS_BACKUP="그래픽 백업 만들기", DELETE_BACKUP="백업 삭제", DELETE_BACKUP_CONFIRM="이 백업을 영구 삭제할까요?", APPLY_PROFILE="프로필 확인 및 적용", PROFILE_APPLY_CONFIRM="개인 프로필을 적용할까요?", PROFILE_APPLY_CONFIRM_TEXT="선택한 그래픽 프로필을 적용할까요?", GRAPHICS_ONLY_NOTICE="인터페이스 및 게임플레이는 재설계 중이라 임시로 숨겨졌습니다.", RESTORE_SELECTED="선택한 백업 복원", BACKUP_LABEL="백업", PROFILE_LABEL="프로필", RIGHT_CLICK_PROFILES="오른쪽 클릭: 프로필 및 백업", PENDING_FPS="전투 후 적용하고 이어서 측정합니다.", MODE_UNIFIED_HELP="어디서나 동일한 균형 그래픽입니다.", MODE_SPLIT_HELP="공격대와 전장용 가벼운 Blizzard 프로필입니다.", MEASURED_LOCALLY="이 캐릭터에서 측정", SELECT_ITEM="항목을 선택하세요", NO_GRAPHICS_PROFILES="저장된 그래픽 프로필이 없습니다.", RESTORE_COMPLETE="그래픽을 복원했습니다.", APPLY_FAILED="설정을 적용하지 못했습니다.",
}
strings.zhCN = {
  APPLY_AND_MEASURE="应用并测量帧率", APPLY_CONFIRM="应用图形设置？", APPLY_CONFIRM_TEXT="应用 %d 项已审核更改？将先创建图形备份。", SETTINGS_APPLIED="图形设置已应用，正在测量帧率…", FPS_RESULT_FORMAT="平均帧率：%d → %d，%+d FPS（%+d%%）", FPS_MEASURING="正在测量帧率…请在原地停留 8 秒。", FPS_MEASURE_HELP="本机应用前后测量；结果是随场景变化的估算值。", FPS_UNAVAILABLE="暂无帧率对比。", FPS_ESTIMATE="本机帧率估算", VISUAL_PREVIEW="均衡图形预览", VISUAL_PREVIEW_NOTE="示意预览：保留清晰轮廓、地面效果和适量粒子。", UNDO="撤销图形更改", UNDO_CONFIRM="恢复之前的图形设置？", UNDO_CONFIRM_TEXT="恢复最新图形备份？将先创建安全备份。", UNDO_UNAVAILABLE="暂无图形备份。", PERSONAL_PROFILES="个人配置", BACKUPS_AND_PROFILES="配置与备份", CREATE_GRAPHICS_BACKUP="创建图形备份", DELETE_BACKUP="删除备份", DELETE_BACKUP_CONFIRM="永久删除此备份？", APPLY_PROFILE="预览并应用配置", PROFILE_APPLY_CONFIRM="应用个人配置？", PROFILE_APPLY_CONFIRM_TEXT="应用所选图形配置？", GRAPHICS_ONLY_NOTICE="界面与游戏功能正在重新设计，暂时隐藏。", RESTORE_SELECTED="恢复所选备份", BACKUP_LABEL="备份", PROFILE_LABEL="配置", RIGHT_CLICK_PROFILES="右键：配置与备份", PENDING_FPS="战斗结束后应用，随后开始测量。", MODE_UNIFIED_HELP="所有场景使用相同的均衡图形。", MODE_SPLIT_HELP="团队和战场使用较轻的 Blizzard 配置。", MEASURED_LOCALLY="在此角色上测量", SELECT_ITEM="请在下方选择项目", NO_GRAPHICS_PROFILES="尚未保存图形配置。", RESTORE_COMPLETE="图形设置已恢复。", APPLY_FAILED="无法应用设置。",
}
strings.zhTW = {
  APPLY_AND_MEASURE="套用並測量幀率", APPLY_CONFIRM="套用圖形設定？", APPLY_CONFIRM_TEXT="套用 %d 項已檢查變更？將先建立圖形備份。", SETTINGS_APPLIED="圖形設定已套用，正在測量幀率…", FPS_RESULT_FORMAT="平均幀率：%d → %d，%+d FPS（%+d%%）", FPS_MEASURING="正在測量幀率…請在原地停留 8 秒。", FPS_MEASURE_HELP="本機套用前後測量；結果是隨場景變化的估算值。", FPS_UNAVAILABLE="尚無幀率比較。", FPS_ESTIMATE="本機幀率估算", VISUAL_PREVIEW="均衡圖形預覽", VISUAL_PREVIEW_NOTE="示意預覽：保留清晰輪廓、地面效果和適量粒子。", UNDO="復原圖形變更", UNDO_CONFIRM="還原之前的圖形設定？", UNDO_CONFIRM_TEXT="還原最新圖形備份？將先建立安全備份。", UNDO_UNAVAILABLE="尚無圖形備份。", PERSONAL_PROFILES="個人設定檔", BACKUPS_AND_PROFILES="設定檔與備份", CREATE_GRAPHICS_BACKUP="建立圖形備份", DELETE_BACKUP="刪除備份", DELETE_BACKUP_CONFIRM="永久刪除此備份？", APPLY_PROFILE="預覽並套用設定檔", PROFILE_APPLY_CONFIRM="套用個人設定檔？", PROFILE_APPLY_CONFIRM_TEXT="套用所選圖形設定檔？", GRAPHICS_ONLY_NOTICE="介面與遊戲功能正在重新設計，暫時隱藏。", RESTORE_SELECTED="還原所選備份", BACKUP_LABEL="備份", PROFILE_LABEL="設定檔", RIGHT_CLICK_PROFILES="右鍵：設定檔與備份", PENDING_FPS="戰鬥結束後套用，隨後開始測量。", MODE_UNIFIED_HELP="所有場合使用相同的均衡圖形。", MODE_SPLIT_HELP="團隊與戰場使用較輕的 Blizzard 設定檔。", MEASURED_LOCALLY="在此角色上測量", SELECT_ITEM="請在下方選擇項目", NO_GRAPHICS_PROFILES="尚未儲存圖形設定檔。", RESTORE_COMPLETE="圖形設定已還原。", APPLY_FAILED="無法套用設定。",
}

for locale, values in pairs(strings) do
  STBS.Locale[locale] = STBS.Locale[locale] or {}
  for key, value in pairs(values) do STBS.Locale[locale][key] = value end
end
