local _, STBS = ...
local function c(key, module, category, values, extra)
  extra = extra or {}; extra.key = key; extra.module = module; extra.category = category; extra.valueType = "numberString"; extra.readable = true; extra.writable = true; extra.portable = true; extra.validValues = values; extra.verifiedClientBuild = "12.0.7.68453"; return extra
end
local levels = { ["0"]=true,["1"]=true,["2"]=true,["3"]=true,["4"]=true,["5"]=true,["6"]=true,["7"]=true,["8"]=true,["9"]=true,["10"]=true }
local graphics = { ["0"]=true,["1"]=true,["2"]=true,["3"]=true,["4"]=true }
STBS.Registry = {
  c("RAIDsettingsEnabled", "graphics", "graphics", { ["0"]=true,["1"]=true }, { valueType="booleanString", officialProfileAllowed=true }),
  c("graphicsShadowQuality","graphics","graphics",graphics,{officialProfileAllowed=true}), c("graphicsLiquidDetail","graphics","graphics",graphics,{officialProfileAllowed=true}), c("graphicsParticleDensity","graphics","graphics",graphics,{officialProfileAllowed=true, minimum=1}), c("graphicsSSAO","graphics","graphics",graphics,{officialProfileAllowed=true}), c("graphicsDepthEffects","graphics","graphics",graphics,{officialProfileAllowed=true}), c("graphicsComputeEffects","graphics","graphics",graphics,{officialProfileAllowed=true}), c("graphicsOutlineMode","graphics","graphics",{["0"]=true,["1"]=true,["2"]=true},{officialProfileAllowed=true,minimum=1}), c("graphicsTextureResolution","graphics","graphics",graphics,{officialProfileAllowed=true}), c("graphicsSpellDensity","graphics","graphics",{["0"]=true,["1"]=true,["2"]=true},{officialProfileAllowed=true,feature="spellDensity"}), c("graphicsProjectedTextures","graphics","graphics",{["0"]=true,["1"]=true},{officialProfileAllowed=true,minimum=1}), c("graphicsViewDistance","graphics","graphics",levels,{officialProfileAllowed=true}), c("graphicsEnvironmentDetail","graphics","graphics",levels,{officialProfileAllowed=true}), c("graphicsGroundClutter","graphics","graphics",levels,{officialProfileAllowed=true}), c("textureFilteringMode","graphics","graphics",{["1"]=true,["2"]=true,["3"]=true,["4"]=true,["5"]=true},{officialProfileAllowed=true}), c("shadowrt","graphics","graphics",{["0"]=true,["1"]=true},{officialProfileAllowed=true}),
  c("ffxAntiAliasingMode","graphics","graphics",graphics,{officialProfileAllowed=true,capability="aa"}),
  c("raidGraphicsShadowQuality","graphics","raidGraphics",graphics,{officialProfileAllowed=true}), c("raidGraphicsLiquidDetail","graphics","raidGraphics",graphics,{officialProfileAllowed=true}), c("raidGraphicsParticleDensity","graphics","raidGraphics",graphics,{officialProfileAllowed=true,minimum=1}), c("raidGraphicsSSAO","graphics","raidGraphics",graphics,{officialProfileAllowed=true}), c("raidGraphicsDepthEffects","graphics","raidGraphics",graphics,{officialProfileAllowed=true}), c("raidGraphicsComputeEffects","graphics","raidGraphics",graphics,{officialProfileAllowed=true}), c("raidGraphicsOutlineMode","graphics","raidGraphics",{["0"]=true,["1"]=true,["2"]=true},{officialProfileAllowed=true,minimum=1}), c("raidGraphicsTextureResolution","graphics","raidGraphics",graphics,{officialProfileAllowed=true}), c("raidGraphicsSpellDensity","graphics","raidGraphics",{["0"]=true,["1"]=true,["2"]=true},{officialProfileAllowed=true,feature="spellDensity"}), c("raidGraphicsProjectedTextures","graphics","raidGraphics",{["0"]=true,["1"]=true},{officialProfileAllowed=true,minimum=1}), c("raidGraphicsViewDistance","graphics","raidGraphics",levels,{officialProfileAllowed=true}), c("raidGraphicsEnvironmentDetail","graphics","raidGraphics",levels,{officialProfileAllowed=true}), c("raidGraphicsGroundClutter","graphics","raidGraphics",levels,{officialProfileAllowed=true}),
  c("cameraSmoothStyle", "interfaceGameplay", "camera", { ["0"]=true,["1"]=true,["2"]=true,["3"]=true }, { officialProfileAllowed=true }),
}
STBS.RegistryByKey = {}; for _, setting in ipairs(STBS.Registry) do STBS.RegistryByKey[setting.key] = setting end
function STBS:GetRegistry(module) local out = {}; for _, s in ipairs(self.Registry) do if not module or s.module == module then table.insert(out,s) end end return out end
